### ISSUE TITLE
CAS doesn't return after logout success

### ISSUE THREAD

**Issue by ldenoix** [Alexandre-T/casguard#2]
Hello,
The application stays on CAS logout page after successful logout, instead of going back to the homepage parameter set in cas_guard.yaml.
It's ok with the following code in CasAuthenticator.php file:
```
    public function onLogoutSuccess(Request $request)
    {
        phpCAS::setDebug($this->cas->getDebug());
        phpCAS::setVerbose($this->cas->isVerbose());
        phpCAS::client(
            $this->cas->getVersion(),
            $this->cas->getHostname(),
            $this->cas->getPort(),
            $this->cas->getUrl()
        );
        phpCAS::setLang($this->cas->getLanguage());

        $uri = $this->router->generate(
            $this->cas->getRouteHomepage(),array(), UrlGeneratorInterface::ABSOLUTE_URL
        );

        phpCAS::logoutWithRedirectService($uri);
    }

```
Thanks

**Comment by Alexandre-T** [comment]
Hi! 

Your code seems good. I would like to test it on some environment and I have to rework the CasAuthenticatorTest::testOnLogout().

**Comment by Alexandre-T** [comment]
As I expected, I have to add some parameters, because some Cas Server does not allow the logoutWithRedirectService (and an admin can choose to not authorized redirection). I will add this and the #3 in a same release.
