### ISSUE TITLE
Proposed : Adding "Internal Symfony SecurityToken Attributes" support auto-update from Cas returned Attributes

### ISSUE THREAD

**Issue by MUbedaSJ** [Alexandre-T/casguard#4]
#3 

Hello,

Thanks you for your good "cas_guard" bundle.
I know is possible you doesn't need "Cas Attribute", but for some users using this "attributes" should be very useful...

If you want to implement this functionality, is very simple, just add this line to your [CasAuthentificator->onAuthenticationSuccess()](https://github.com/Alexandre-T/casguard/blob/1255a8abb71f40cafeea5f600329a28baa1747c3/Security/CasAuthenticator.php#L159) before "return null;" :

>         $token->setAttributes(phpCAS::getAttributes());"

Please see result with Security SF on next 2 pictures (before/after)
(no configuration need : all available CAS attributes will be directly integrated into Symfony SecurityToken Attributes)

Before:
![before](https://user-images.githubusercontent.com/41287012/42757307-d299376c-88ff-11e8-95a0-c3a9ed518542.png)

After:
![after](https://user-images.githubusercontent.com/41287012/42757305-d280db0e-88ff-11e8-939e-19263c904c87.png)

I'v tested and confirm working in SF 3.4 and 4.1..

**Comment by Alexandre-T** [comment]
Thanks for your tests and this feature. I will add it in next release. If I could, I will add it before end of month.

**Comment by Alexandre-T** [comment]
I implemented your code, but I encountered some bugs. Sometimes, phpCAS is not initialized, so I add a test:
```
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if (phpCAS::isInitialized()) {
            $token->setAttributes(phpCAS::getAttributes());
        }

        return null;
    }
```

You can use it with dev version.

It will be cool, if you confirm me it is working, because I cannot test attributes, our Cas Server is configured to never return attributes.
