### ISSUE TITLE
PHP7.2 compatibility 

### ISSUE THREAD

**Issue by MUbedaSJ** [Alexandre-T/casguard#5]
Hello,

I just try to use it on SF 3.4 & 4.1 with PHP 7.2, and i take a warning exception on CasAuthentificator.php line 97 https://github.com/Alexandre-T/casguard/blob/1255a8abb71f40cafeea5f600329a28baa1747c3/Security/CasAuthenticator.php#L97 (warning come using "count()" function) :

It seem PHP 7.2 not allow count on null or "non iterable" object (cf http://php.net/manual/en/function.count.php or http://php.net/manual/en/migration72.incompatible.php)

I've locally patch this line like this and seem resolve this problem :

            if (is_array($this->cas->getAllowedClients()) ? count($this->cas->getAllowedClients()) : false) {

Another possibility can be inspired by "symfony/monolog-bunble" patch (using 'empty()' instead of 'count()'): 
 https://github.com/symfony/monolog-bundle/commit/ab76969308496917175374ac734d474733c59757

Best Regards.

**Comment by Alexandre-T** [comment]
Thank you @MUbedaSJ , I think the monolog-bundle patch using empty is more elegant. I will test it and pull a request before end of month.

**Comment by Alexandre-T** [comment]
This warning is fixed in dev version.
