### ISSUE TITLE
Fail to Install with symfony 4.2

### ISSUE THREAD

**Issue by MUbedaSJ** [Alexandre-T/casguard#6]
Hello, 

I've composer require error on 4.2 installation procedure;
My "composer.json" have more recent "yaml" : 

> "symfony/yaml": "4.2.*"

Installation stop alerting:

> Using version ^0.2.0 for alexandret/phpcas-guard-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
    - Installation request for alexandret/phpcas-guard-bundle ^0.2.0 -> satisfiable by alexandret/phpcas-guard-bundle[0.2.0].
    - alexandret/phpcas-guard-bundle 0.2.0 requires symfony/yaml ^3.3 -> no matching package found.

Should your composer.json have require like this
>     "symfony/framework-bundle": "~3.4 | ^4.*",
instead of
>     "symfony/framework-bundle": "~3.4 | ^4.0",

Best regards

**Comment by Alexandre-T** [comment]
I have developped new features to be compliant with symfony 4.*
Instead of casguard [version 0.2.1](https://github.com/Alexandre-T/casguard/releases/tag/0.2.1), you could use the [dev version](https://github.com/Alexandre-T/casguard/tree/dev)
